### ISSUE TITLE
Assetic filter not run on cache:clear

### ISSUE THREAD

**Issue by bendavies** [hearsayit/HearsayRequireJSBundle#14]
Since Assetic does a asset dump on cache:clear, I would expect RequireJSOptimizerFilter to run too, but it doesn't appear to.

Haven't done much digging, as to why yet.

**Comment by ihortymoshenko** [comment]
@bendavies, I'm not sure that the described behaviour is normal. Anyway, I've checked the `assetic:dump` command and all works as expected.
