### ISSUE TITLE
Errors with Laravel 4.  (phpunit tests)

### ISSUE THREAD

**Issue by ozone1979** [hearsayit/HearsayRequireJSBundle#22]
Time: 11 seconds, Memory: 9.75Mb

There were 3 errors:

1) Hearsay\RequireJSBundle\Tests\Templating\Helper\RequireJSHelperTest::testDefaultInitialization
Missing argument 4 for Hearsay\RequireJSBundle\Templating\Helper\RequireJSHelper::__construct(), called in C:\wamp\www_test\inc\core\vendor\hearsay\require-js-bundle\Hearsay\RequireJSBundle\Tests\Templating\Helper\RequireJSHelperTest.php on line 54 and defined

C:\wamp\www_test\inc\core\vendor\hearsay\require-js-bundle\Hearsay\RequireJSBundle\Templating\Helper\RequireJSHelper.php:66
C:\wamp\www_test\inc\core\vendor\hearsay\require-js-bundle\Hearsay\RequireJSBundle\Tests\Templating\Helper\RequireJSHelperTest.php:54

2) Hearsay\RequireJSBundle\Tests\Templating\Helper\RequireJSHelperTest::testConfigurationSuppressed
Missing argument 4 for Hearsay\RequireJSBundle\Templating\Helper\RequireJSHelper::__construct(), called in C:\wamp\www_test\inc\core\vendor\hearsay\require-js-bundle\Hearsay\RequireJSBundle\Tests\Templating\Helper\RequireJSHelperTest.php on line 75 and defined

C:\wamp\www_test\inc\core\vendor\hearsay\require-js-bundle\Hearsay\RequireJSBundle\Templating\Helper\RequireJSHelper.php:66
C:\wamp\www_test\inc\core\vendor\hearsay\require-js-bundle\Hearsay\RequireJSBundle\Tests\Templating\Helper\RequireJSHelperTest.php:75

3) Hearsay\RequireJSBundle\Tests\Templating\Helper\RequireJSHelperTest::testMainScriptIncluded
Missing argument 4 for Hearsay\RequireJSBundle\Templating\Helper\RequireJSHelper::__construct(), called in C:\wamp\www_test\inc\core\vendor\hearsay\require-js-bundle\Hearsay\RequireJSBundle\Tests\Templating\Helper\RequireJSHelperTest.php on line 97 and defined

C:\wamp\www_test\inc\core\vendor\hearsay\require-js-bundle\Hearsay\RequireJSBundle\Templating\Helper\RequireJSHelper.php:66
C:\wamp\www_test\inc\core\vendor\hearsay\require-js-bundle\Hearsay\RequireJSBundle\Tests\Templating\Helper\RequireJSHelperTest.php:97

**Comment by ihortymoshenko** [comment]
The constructor method does not include the fourth argument. Perhaps, it is depends on Laravel 4 even if the last uses Symfony components. I also did not found the constructor method impelementations in the following class `Symfony\Component\Templating\Helper\Helper`. Please provide more information. Thanks!
