### ISSUE TITLE
Service definition "hearsay_require_js.optimizer_filter" not exists

### ISSUE THREAD

**Issue by Koc** [hearsayit/HearsayRequireJSBundle#23]
Method `addExternalNamespaceMapping` should check for this definition before calling 

``` php
$filter = $container->getDefinition('hearsay_require_js.optimizer_filter');
$filter->addMethodCall('addExternal', array($path));
```

**Comment by ihortymoshenko** [comment]
Can you write a step by step what you did to get the error message? Thanks!

**Comment by Koc** [comment]
I've just added external js

**Comment by ihortymoshenko** [comment]
Thanks for the feedback. I will check ASAP.
