### ISSUE TITLE
Coffeescript support

### ISSUE THREAD

**Issue by cbourgois** [hearsayit/HearsayRequireJSBundle#31]
I'm not sure what I read. Is it possible to use coffee script code,convert it in javascript and optimize it in a single AMD js file ?
If yes, what is the typical configuration?

**Comment by ihortymoshenko** [comment]
@cbourgois, we have PR https://github.com/hearsayit/HearsayRequireJSBundle/pull/17 with changes which allow to use files with any extensions. So they are will be accessable for `RequireJS`. Will it be enough?

**Comment by ihortymoshenko** [comment]
@cbourgois, I've read the `RequireJS` docs again and I think there is no sense in adding such ability. You should use the `require-cs` loader plugin for the `RequireJS`. See https://github.com/jrburke/require-cs for docs.

**Comment by arnaud-lb** [comment]
@IgorTimoshenko please see my comment at https://github.com/hearsayit/HearsayRequireJSBundle/pull/17#issuecomment-21314558
