### ISSUE TITLE
Optiomization with paths that contains dot in their name

### ISSUE THREAD

**Issue by vkartaviy** [hearsayit/HearsayRequireJSBundle#35]
Due to command line argument syntax limitation (http://requirejs.org/docs/optimization.html#basics) it's not possible to provide path with dot inside name, for example *backbone.wreqr" so it should be embed inside build profile file together with shim configuration.

**Comment by ihortymoshenko** [comment]
@vkartaviy, I honestly don't like current configuration for `r.js` and I think about adding support for build file but I don't know when exactly this will be available :)

**Comment by ihortymoshenko** [comment]
@vkartaviy, I've rewritten the `r.js` filter for Assetic. Now will be generated dynamically the build profile's file, so we wouldn't have the issue with dots in the modules' names.
