### ISSUE TITLE
Scripts are not accessible

### ISSUE THREAD

**Issue by AsaAyers** [hearsayit/HearsayRequireJSBundle#4]
The documentation indicates that scripts should be kept in %kernel.root_dir%/scripts and Resources/scripts under your bundle. Neither of these are accessible and I don't see anything in your bundle that handles requests to /app_dev.php/js. I want to keep the original javascript files private and only expose optimized/uglified files. Am I missing something or does this bundle not do that?

**Comment by AsaAyers** [comment]
I sort of found the problem but not a great solution yet. If I leave the base url alone it always requests js/namespace/script.js. I changed my config_dev to use /app_dev.php/js as the base_url, but assectic then uses that when building the routes. so now my files are only accessible when requesting /app_dev.php/app_dev.php/js/namespace/script.js

Right now I'm working around this by configuring require manually, but I dont' think this is a permanent solution.

<script type='text/javascript'>
        var require = {{ require_js.config|json_encode|raw }};
        require.baseUrl = '/app_dev.php/' + require.baseUrl;
    </script>


{% javascripts filter='?requirejs' '@MyBundle/Resources/scripts/main.js' output="js/main.js" %}
{{ require_js_initialize({ 'configure' : false, 'main' : asset_url }) }}
{% endjavascripts %}

**Comment by AsaAyers** [comment]
Your fix in https://github.com/hearsayit/HearsayRequireJSBundle/issues/1 solved my problem here too. I think my problem was caused by trying to use bigethan's workaround

**Comment by kmontag** [comment]
Yep, files in your configured directories (%kernel.root_dir%/scripts and */Resources/scripts in the README) are served as Assetic assets.  So there's no bundle-specific routing - you can check out the Hearsay\RequireJSBundle\Factory namespace to see how the assets and their names are generated.

I'm adding an option to hide unoptimized Javascript files, which should be useful in production environments :)
