### ISSUE TITLE
How can I use modules for r.js?

### ISSUE THREAD

**Issue by jifeon** [hearsayit/HearsayRequireJSBundle#54]
I have a multi-page project and want organize my scripts following [this example](https://github.com/requirejs/example-multipage-shim). But when I specify "modules" section in the [build profile](https://github.com/jrburke/r.js/blob/master/build/example.build.js) for r.js, optimizer throws an error:

Optimization failed: Error: If the "modules" option is used, then there should be a "dir" option set and "out" should not be used since "out" is only for single file optimization output.
    at Function.build.createConfig (/home/abalakirev/www40/my-ru/app/Resources/js-vendors/js/RequireJS/r.js:23253:19)

If I set the "dir" option, optimizer says "out" option is incompatible with "modules".

What I'm doing wrong? What the true way for organizing scripts in a multi-page application using your bundle?

**Comment by apsavin** [comment]
What if I'll just add a condition [here](https://github.com/hearsayit/HearsayRequireJSBundle/blob/master/Assetic/Filter/RJsFilter.php#L239)?

**Comment by ihortymoshenko** [comment]
This issue is related to the issue https://github.com/hearsayit/HearsayRequireJSBundle/issues/43. So I think it should be resolved within the confines of the issue https://github.com/hearsayit/HearsayRequireJSBundle/issues/43. If you have any fresh ideas how to do it, feel free to contribute.
